/*
* generated by Xtext
*/
package meta.sll.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import meta.sll.services.SLLGrammarAccess;

public class SLLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SLLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected meta.sll.parser.antlr.internal.InternalSLLParser createParser(XtextTokenStream stream) {
		return new meta.sll.parser.antlr.internal.InternalSLLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}
	
	public SLLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SLLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
