/*
 * generated by Xtext
 */
package meta.sll;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SLLRuntimeModule extends meta.sll.AbstractSLLRuntimeModule {

}
