/*
* generated by Xtext
*/
package meta.sll;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SLLStandaloneSetup extends SLLStandaloneSetupGenerated{

	public static void doSetup() {
		new SLLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

