/*
 * generated by Xtext
 */
package meta.sll.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SLLUiModule extends meta.sll.ui.AbstractSLLUiModule {
	public SLLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
