/*
 * generated by Xtext
 */
package meta.sll.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import meta.sll.ui.internal.SLLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SLLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SLLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SLLActivator.getInstance().getInjector(SLLActivator.META_SLL_SLL);
	}
	
}
