/*
 * generated by Xtext
 */
package meta.sll.ui.contentassist

import meta.sll.ui.contentassist.AbstractSLLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class SLLProposalProvider extends AbstractSLLProposalProvider {
}
